version: "3"

tasks:
  build:
    cmds:
      - go build -o bin/trad trad.go

  run:
    cmds:
      - task build && ./bin/trad {{ .CLI_ARGS }}

  rel:
    desc: Push a new release
    cmds:
      - git tag {{ .CLI_ARGS }}
      - git push origin {{ .CLI_ARGS }}
